// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: togds_userRpc.proto

package togds_userRpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginRpcre_Login_FullMethodName = "/togds_userRpc.loginRpcre/Login"
)

// LoginRpcreClient is the client API for LoginRpcre service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginRpcreClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
}

type loginRpcreClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginRpcreClient(cc grpc.ClientConnInterface) LoginRpcreClient {
	return &loginRpcreClient{cc}
}

func (c *loginRpcreClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, LoginRpcre_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginRpcreServer is the server API for LoginRpcre service.
// All implementations must embed UnimplementedLoginRpcreServer
// for forward compatibility.
type LoginRpcreServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	mustEmbedUnimplementedLoginRpcreServer()
}

// UnimplementedLoginRpcreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginRpcreServer struct{}

func (UnimplementedLoginRpcreServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginRpcreServer) mustEmbedUnimplementedLoginRpcreServer() {}
func (UnimplementedLoginRpcreServer) testEmbeddedByValue()                    {}

// UnsafeLoginRpcreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginRpcreServer will
// result in compilation errors.
type UnsafeLoginRpcreServer interface {
	mustEmbedUnimplementedLoginRpcreServer()
}

func RegisterLoginRpcreServer(s grpc.ServiceRegistrar, srv LoginRpcreServer) {
	// If the following call pancis, it indicates UnimplementedLoginRpcreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginRpcre_ServiceDesc, srv)
}

func _LoginRpcre_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginRpcreServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginRpcre_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginRpcreServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginRpcre_ServiceDesc is the grpc.ServiceDesc for LoginRpcre service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginRpcre_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "togds_userRpc.loginRpcre",
	HandlerType: (*LoginRpcreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginRpcre_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "togds_userRpc.proto",
}
