// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: togds_userRpc.proto

package loginrpcre

import (
	"context"

	"togds/service/togds_user/rpc/togds_userRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq  = togds_userRpc.LoginReq
	LoginResp = togds_userRpc.LoginResp

	LoginRpcre interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultLoginRpcre struct {
		cli zrpc.Client
	}
)

func NewLoginRpcre(cli zrpc.Client) LoginRpcre {
	return &defaultLoginRpcre{
		cli: cli,
	}
}

func (m *defaultLoginRpcre) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := togds_userRpc.NewLoginRpcreClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
