// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: togds_userRpc.proto

package server

import (
	"context"

	"togds/service/togds_user/rpc/internal/logic"
	"togds/service/togds_user/rpc/internal/svc"
	"togds/service/togds_user/rpc/togds_userRpc"
)

type LoginRpcreServer struct {
	svcCtx *svc.ServiceContext
	togds_userRpc.UnimplementedLoginRpcreServer
}

func NewLoginRpcreServer(svcCtx *svc.ServiceContext) *LoginRpcreServer {
	return &LoginRpcreServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginRpcreServer) Login(ctx context.Context, in *togds_userRpc.LoginReq) (*togds_userRpc.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
