// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: togdsuserrpc.proto

package server

import (
	"context"

	"togds/service/user/rpc/internal/logic"
	"togds/service/user/rpc/internal/svc"
	"togds/service/user/rpc/togdsuserrpc"
)

type AuthRpcreServer struct {
	svcCtx *svc.ServiceContext
	togdsuserrpc.UnimplementedAuthRpcreServer
}

func NewAuthRpcreServer(svcCtx *svc.ServiceContext) *AuthRpcreServer {
	return &AuthRpcreServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthRpcreServer) Login(ctx context.Context, in *togdsuserrpc.LoginReq) (*togdsuserrpc.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
