// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.19.4
// source: togds_auth.proto

package togds_auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenReq) Reset() {
	*x = CheckTokenReq{}
	mi := &file_togds_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenReq) ProtoMessage() {}

func (x *CheckTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_togds_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenReq.ProtoReflect.Descriptor instead.
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return file_togds_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CheckTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResp) Reset() {
	*x = CheckTokenResp{}
	mi := &file_togds_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResp) ProtoMessage() {}

func (x *CheckTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_togds_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResp.ProtoReflect.Descriptor instead.
func (*CheckTokenResp) Descriptor() ([]byte, []int) {
	return file_togds_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CheckTokenResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckTokenResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckTokenResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshReq) Reset() {
	*x = RefreshReq{}
	mi := &file_togds_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshReq) ProtoMessage() {}

func (x *RefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_togds_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshReq.ProtoReflect.Descriptor instead.
func (*RefreshReq) Descriptor() ([]byte, []int) {
	return file_togds_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResp) Reset() {
	*x = RefreshResp{}
	mi := &file_togds_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResp) ProtoMessage() {}

func (x *RefreshResp) ProtoReflect() protoreflect.Message {
	mi := &file_togds_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResp.ProtoReflect.Descriptor instead.
func (*RefreshResp) Descriptor() ([]byte, []int) {
	return file_togds_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RefreshResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_togds_auth_proto protoreflect.FileDescriptor

var file_togds_auth_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x22, 0x25,
	0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x22, 0x0a, 0x0a, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x0b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x8f,
	0x01, 0x0a, 0x0c, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x41, 0x75, 0x74, 0x68, 0x52, 0x70, 0x63, 0x12,
	0x43, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x2e,
	0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x74, 0x6f, 0x67, 0x64, 0x73,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12,
	0x16, 0x2e, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x74, 0x6f, 0x67, 0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_togds_auth_proto_rawDescOnce sync.Once
	file_togds_auth_proto_rawDescData = file_togds_auth_proto_rawDesc
)

func file_togds_auth_proto_rawDescGZIP() []byte {
	file_togds_auth_proto_rawDescOnce.Do(func() {
		file_togds_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_togds_auth_proto_rawDescData)
	})
	return file_togds_auth_proto_rawDescData
}

var file_togds_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_togds_auth_proto_goTypes = []any{
	(*CheckTokenReq)(nil),  // 0: togds_auth.CheckTokenReq
	(*CheckTokenResp)(nil), // 1: togds_auth.CheckTokenResp
	(*RefreshReq)(nil),     // 2: togds_auth.RefreshReq
	(*RefreshResp)(nil),    // 3: togds_auth.RefreshResp
}
var file_togds_auth_proto_depIdxs = []int32{
	0, // 0: togds_auth.togdsAuthRpc.CheckToken:input_type -> togds_auth.CheckTokenReq
	2, // 1: togds_auth.togdsAuthRpc.Refresh:input_type -> togds_auth.RefreshReq
	1, // 2: togds_auth.togdsAuthRpc.CheckToken:output_type -> togds_auth.CheckTokenResp
	3, // 3: togds_auth.togdsAuthRpc.Refresh:output_type -> togds_auth.RefreshResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_togds_auth_proto_init() }
func file_togds_auth_proto_init() {
	if File_togds_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_togds_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_togds_auth_proto_goTypes,
		DependencyIndexes: file_togds_auth_proto_depIdxs,
		MessageInfos:      file_togds_auth_proto_msgTypes,
	}.Build()
	File_togds_auth_proto = out.File
	file_togds_auth_proto_rawDesc = nil
	file_togds_auth_proto_goTypes = nil
	file_togds_auth_proto_depIdxs = nil
}
