// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: togds_auth.proto

package server

import (
	"context"

	"togds/service/togds_auth/rpc/internal/logic"
	"togds/service/togds_auth/rpc/internal/svc"
	"togds/service/togds_auth/rpc/togds_auth"
)

type TogdsAuthRpcServer struct {
	svcCtx *svc.ServiceContext
	togds_auth.UnimplementedTogdsAuthRpcServer
}

func NewTogdsAuthRpcServer(svcCtx *svc.ServiceContext) *TogdsAuthRpcServer {
	return &TogdsAuthRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TogdsAuthRpcServer) CheckToken(ctx context.Context, in *togds_auth.CheckTokenReq) (*togds_auth.CheckTokenResp, error) {
	l := logic.NewCheckTokenLogic(ctx, s.svcCtx)
	return l.CheckToken(in)
}

func (s *TogdsAuthRpcServer) Refresh(ctx context.Context, in *togds_auth.RefreshReq) (*togds_auth.RefreshResp, error) {
	l := logic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}
