// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5

package types

type LoginReq struct {
	Username string `header: "username"`
	Password string `header: "password"`
}

type LoginResp struct {
	Code int64  `json: "code"`
	Msg  string `json: "msg"`
	Data string `json "data"`
}

type UserAddReq struct {
	Username string `header: "username"`
	Password string `header: "password"`
	Phone    string `header: "phone"`
	Email    string `header "email"`
}

type UserListResp struct {
	Code int64  `json: "code"`
	Msg  string `json: "msg"`
	Data string `json "data"`
}
