// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: authrpc.proto

package server

import (
	"context"

	"togds/service/auth/rpc/authRpc"
	"togds/service/auth/rpc/internal/logic"
	"togds/service/auth/rpc/internal/svc"
)

type AuthRpcreServer struct {
	svcCtx *svc.ServiceContext
	authRpc.UnimplementedAuthRpcreServer
}

func NewAuthRpcreServer(svcCtx *svc.ServiceContext) *AuthRpcreServer {
	return &AuthRpcreServer{
		svcCtx: svcCtx,
	}
}


func (s *AuthRpcreServer) CheckToken(ctx context.Context, in *authRpc.CheckTokenReq) (*authRpc.CheckTokenResp, error) {
	l := logic.NewCheckTokenLogic(ctx, s.svcCtx)
	return l.CheckToken(in)
}

func (s *AuthRpcreServer) Refresh(ctx context.Context, in *authRpc.RefreshReq) (*authRpc.RefreshResp, error) {
	l := logic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}
